=== TeteV/XmlPlayasLPGC/public_html/playasLPGC.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.tetito.com"
xmlns="https://www.tetito.com"
elementFormDefault="qualified">
    
    <xs:element name="response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resources">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="str">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string"/>
                                            </xs:simpleType>                                          
                                        </xs:element>
                                        
                                        <xs:element name="date" > <!--type="xs:date" minOccurs="0" -->
                                            <xs:simpleType >
                                                <xs:restriction base="xs:date"/>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== TeteV/XmlPlayasLPGC/public_html/playaslpgc.xml
<?xml version="1.0" encoding="UTF-8"?>

<response xmlns="https://www.tetito.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.tetito.com playaslpgc.xsd">

    <resources name="response">
        <resource>
            <str name="lpgc:telefono">+34 928446528 29</str>
            <str name="dc:title">Las Canteras</str>
            <str name="lpgc:direccion"/>
            <str name="lpgc:web">www.lpamar.com</str>
            <str name="geo:lat">28.140241</str>
            <date name="dc:modified">2020-04-02T09:04:15.657Z</date>
            <str name="dc:description">
                La playa de Las Canteras es una de las playas urbanas más importantes de España, ganadora de varios galardones nacionales e internacionales de calidad, entre ellos,  la Q de Calidad Turística.
                La playa de Las Canteras se extiende desde La Puntilla hasta el Auditorio Alfredo Kraus, un recorrido de tres kilómetros en el que se distinguen varias zonas, cada una con sus peculiaridades. La Cícer (el paraíso surfero), Peña La Vieja (con una zona de rocas llena de vida), Playa Chica y Muro Marrero (la más familiar), Playa Grande (turística por excelencia) y La Puntilla (último reducto de pescadores).
                La Barra, un arrecife que corre en paralelo a más de la mitad de la playa, se constituye en un auténtico rompeolas natural y aporta mayor seguridad para el baño.
                Pasear sobre la fina arena rubia de Las Canteras, cuando la marea baja deja a la vista todo tipo de formaciones rocosas, y por las tardes disfrutar de la experiencia de sus atardeceres son experiencias que no se pueden perder. </str>
            <str name="dc:identifier">386</str>
            <str name="lpgc:pois">28.140241, -15.436142</str>
            <str name="geo:long">-15.436142</str>
            <str name="uri">http://datosabiertos.laspalmasgc.es/api/datos/playas/386.xml</str>
        </resource>
        
        <resource>
            <str name="lpgc:telefono"/>
            <str name="dc:title">El Confital</str>
            <str name="lpgc:direccion">El Confital 
                35009 Las Palmas de Gran Canaria</str>
            <str name="lpgc:web"/>
            <str name="geo:lat">28.1590482</str>
            <date name="dc:modified">2020-04-02T09:04:15.657Z</date>
            <str name="dc:description">Está situada en la península de La Isleta, Paisaje Natural Protegido, y es la prolongación natural de la Playa de Las Canteras.
                Es admirada por la limpieza de sus aguas, la belleza de sus rocas y acantilados y la tranquilidad que ofrece a los bañistas. Además la perfección de sus olas es un reclamo perfecto para los aficionados al surf, al windsurf y al bodyboard (con olas de nivel experto, entre 1,5 y más de 3 metros). </str>
            <str name="dc:identifier">387</str>
            <str name="lpgc:pois">28.1590482, -15.435334099999977</str>
            <str name="geo:long">-15.435334099999977</str>
            <str name="uri">http://datosabiertos.laspalmasgc.es/api/datos/playas/387.xml</str>
        </resource>
        
        <resource>
            <str name="lpgc:telefono"/>
            <str name="dc:title">Las Alcaravaneras</str>
            <str name="lpgc:direccion">Las Alcaravaneras 
                35006 Las Palmas de Gran Canaria</str>
            <str name="lpgc:web"/>
            <str name="geo:lat">28.1303647</str>
            <date name="dc:modified">2020-04-02T09:04:15.657Z</date>
            <str name="dc:description">La playa de las Alcaravaneras, de algo más de medio kilómetro de extensión, está situada junto al muelle deportivo de la ciudad, bordeada por un paseo marítimo y flanqueada por dos de los clubes náuticos de Las Palmas de Gran Canaria. La tranquilidad de sus aguas, al abrigo del Puerto de La Luz y Las Palmas, permite la práctica de distintas modalidades deportivas en el mar.
                Es una de las mejores playas portuarias de España y la calidad de sus aguas está avalada por controles periódicos. Sobre su arena se desarrolla una continua actividad deportiva. La playa cuenta con un dentro de tecnificación deportiva de voleyplaya y se practican todo tipo de actividades náuticas.
                En cuanto a sus instalaciones, cuenta con un puesto de socorrismo, baños, duchas,  acceso para personas de movilidad reducida y un parque infantil. Está muy cerca de la zona comercial de Mesa y López.
            </str>
            <str name="dc:identifier">388</str>
            <str name="lpgc:pois">28.1303647, -15.429139899999996</str>
            <str name="geo:long">-15.429139899999996</str>
            <str name="uri">http://datosabiertos.laspalmasgc.es/api/datos/playas/388.xml</str>
        </resource>
        
        <resource>
            <str name="lpgc:telefono">+34 928446528 
                +34 928446529</str>
            <str name="dc:title">La Puntilla (San Cristóbal)</str>
            <str name="lpgc:direccion"/>
            <str name="lpgc:web">www.lpamar.com</str>
            <str name="geo:lat">28.075939</str>
            <date name="dc:modified">2020-04-02T09:04:15.657Z</date>
            <str name="dc:description">La Playa de La Puntilla se sitúa junto al muelle pesquero del barrio marinero de San Cristóbal, en la entrada sur de Las Palmas de Gran Canaria.  Es una pequeña cala, de arena negra, de unos 50 metros. Una playa de carácter familiar y de corrientes tranquilas, ya que está al abrigo del muelle de pescadores.
                El litoral de San Cristóbal mira también al horizonte desde una playa de callaos, flanqueada por el Castillo de San Pedro (S. XVI), declarado Monumento Histórico Artístico, que era usada antiguamente por los pescadores del barrio para lanzar las redes del chinchorro (un arte de pesca que ya no se permite). Hoy en día la playa es frecuentada también por surferos atraídos por su oleaje.</str>
            <str name="dc:identifier">390</str>
            <str name="lpgc:pois">28.075939, -15.414423</str>
            <str name="geo:long">-15.414423</str>
            <str name="uri">http://datosabiertos.laspalmasgc.es/api/datos/playas/390.xml</str>
        </resource>
        
        <resource>
            <str name="lpgc:telefono">+34 928446528 29</str>
            <str name="dc:title">La Laja</str>
            <str name="lpgc:direccion"/>
            <str name="lpgc:web">www.lpamar.com</str>
            <str name="geo:lat">28.059292944067668</str>
            <date name="dc:modified">2020-04-02T09:04:15.657Z</date>
            <str name="dc:description">Es la entrada sur de la ciudad. Un conjunto escultórico de 9 metros de alto que representa al dios Tritón da la bienvenida a la playa y a la ciudad desde su privilegiado mirador, que permite observar todo el litoral de la capital de la isla, hasta la formación volcánica de La Isleta.
                La Laja, es una playa de 1.200 metros de largo, con oleaje moderado y arena fina negra proveniente de los fondos marinos cercanos. Aquí se puede disfrutar de un entorno abierto al mar al pie de unas singulares montañas, y rodeada de formaciones rocosas. Al estar orientada al este, desde ella se observan unos excelentes amaneceres.
                Es una playa ideal para pasear.
                Piscinas de La Laja
                La Playa de La Laja cuenta con un entorno de piscinas naturales que se han convertido en uno de los principales atractivos del litoral de la capital. Cuenta con tres equipamientos: una piscina infantil natural en forma de media luna, otra piscina adaptada a deportes reglados de 50 metros de longitud y una tercera piscina familiar. Este entorno ha potenciadola integración del mar en la ciudad y cuenta con recursos  de ocio, como un mirador acondicionado para el avistamiento de aves, zonas de sombra y nuevos espacios para tomar el sol. El acceso peatonal se realiza, desde la Avenida Marítima de la capital, a través de un paseo accesible.</str>
            <str name="dc:identifier">389</str>
            <str name="lpgc:pois">28.059292944067668, -15.419483731787068</str>
            <str name="geo:long">-15.419483731787068</str>
            <str name="uri">http://datosabiertos.laspalmasgc.es/api/datos/playas/389.xml</str>
        </resource>
        
    </resources>
</response>
